/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logica.Clases.Archivo;
import Logica.Estructuras.Lista;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andre
 */
public class Pantalla2 extends javax.swing.JFrame {

    private Lista<Archivo> archivos;
    
    /**
     * Creates new form Pantalla2
     */
    public Pantalla2(Lista<Archivo> archivos) {
        initComponents();
        this.archivos = archivos;
        actualizarTabla(archivos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAsignacionArchivos = new javax.swing.JTable();
        creationButton = new javax.swing.JButton();
        deletionButton = new javax.swing.JButton();
        deletionTextField = new javax.swing.JTextField();
        newFileNameField = new javax.swing.JTextField();
        newFileContentField = new javax.swing.JTextField();
        newFileIDField = new javax.swing.JTextField();
        newFileSizeField = new javax.swing.JTextField();
        newFileIField = new javax.swing.JTextField();
        newFileJField = new javax.swing.JTextField();
        fileFilterByIDField = new javax.swing.JTextField();
        filterButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaAsignacionArchivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Número de Bloques", "Ubicación del Primer Bloque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaAsignacionArchivos);
        if (tablaAsignacionArchivos.getColumnModel().getColumnCount() > 0) {
            tablaAsignacionArchivos.getColumnModel().getColumn(0).setResizable(false);
            tablaAsignacionArchivos.getColumnModel().getColumn(1).setResizable(false);
            tablaAsignacionArchivos.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 430, 250));

        creationButton.setText("Crear");
        creationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creationButtonActionPerformed(evt);
            }
        });
        jPanel1.add(creationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        deletionButton.setText("Eliminar");
        deletionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletionButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deletionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        deletionTextField.setText("ID Archivo a Eliminar");
        deletionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletionTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(deletionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 140, -1));

        newFileNameField.setText("Nombre Archivo");
        newFileNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(newFileNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 140, -1));

        newFileContentField.setText("Contenido Archivo");
        newFileContentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileContentFieldActionPerformed(evt);
            }
        });
        jPanel1.add(newFileContentField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 140, -1));

        newFileIDField.setText("ID Archivo");
        newFileIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileIDFieldActionPerformed(evt);
            }
        });
        jPanel1.add(newFileIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 140, -1));

        newFileSizeField.setText("Longitud Archivo");
        newFileSizeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileSizeFieldActionPerformed(evt);
            }
        });
        jPanel1.add(newFileSizeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 140, -1));

        newFileIField.setText("Posición \"I\" Archivo");
        newFileIField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileIFieldActionPerformed(evt);
            }
        });
        jPanel1.add(newFileIField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 140, -1));

        newFileJField.setText("Posición \"J\" Archivo");
        newFileJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileJFieldActionPerformed(evt);
            }
        });
        jPanel1.add(newFileJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 140, -1));

        fileFilterByIDField.setText("ID de Filtro");
        fileFilterByIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileFilterByIDFieldActionPerformed(evt);
            }
        });
        jPanel1.add(fileFilterByIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 140, -1));

        filterButton.setText("Buscar");
        filterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButtonActionPerformed(evt);
            }
        });
        jPanel1.add(filterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void deletionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletionButtonActionPerformed
        try {
            int id = Integer.parseInt(deletionTextField.getText());
            borrarArchivo(id);
            actualizarTabla(archivos);

        } catch (NumberFormatException e) {
            deletionTextField.setText("No válido.");
            System.out.println("Error: El texto ingresado no es un numero valido.");
        }    
    }//GEN-LAST:event_deletionButtonActionPerformed

    private void newFileNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newFileNameFieldActionPerformed

    private void creationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creationButtonActionPerformed

    private void newFileContentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileContentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newFileContentFieldActionPerformed

    private void newFileIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newFileIDFieldActionPerformed

    private void deletionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletionTextFieldActionPerformed

    private void newFileSizeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileSizeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newFileSizeFieldActionPerformed

    private void newFileIFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileIFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newFileIFieldActionPerformed

    private void newFileJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newFileJFieldActionPerformed

    private void fileFilterByIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileFilterByIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileFilterByIDFieldActionPerformed

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed
        try{
            Lista<Archivo> lista_filtrada = filtrarArchivos(Integer.parseInt(fileFilterByIDField.getText()));
            
            // SOUT TEMPORAL PARA PRUEBAS
            for (int i = 0; i < lista_filtrada.size(); i++) {
                System.out.println(lista_filtrada.get(i).getId()+" Check");
            }
            // SOUT TEMPORAL PARA PRUEBAS
            
        }catch (NumberFormatException e) {
            fileFilterByIDField.setText("No válido.");
            System.out.println("Error: El texto ingresado no es un numero valido.");
        }
        
    }//GEN-LAST:event_filterButtonActionPerformed

    public void borrarArchivo(int idArchivo){
        boolean existe = false;
        for (int i = 0; i < this.archivos.size(); i++) {
            if (archivos.get(i).getId() == idArchivo) {
                archivos.deleteByIndex(i);
                existe = true;
                deletionTextField.setText("Eliminado.");
            }
            
            if (!existe) {
                deletionTextField.setText("No existe.");
            }
        }
    }
    
    public void actualizarTabla(Lista<Archivo> archivos) {
        System.out.println("Longitud de la lista de archivos: "+archivos.size());
        DefaultTableModel model = (DefaultTableModel) tablaAsignacionArchivos.getModel();
        model.setRowCount(0); // Limpiar la tabla existente. Así se evitan duplicados.

        for (int i = 0; i < archivos.size(); i++) {
            Archivo archivo = archivos.get(i);
            
            // Para verificar si el archivo ya está en la tabla de asignación de archivos
            boolean existe = false;
            for (int j = 0; j < model.getRowCount(); j++) {
                String nombreEnTabla = (String) model.getValueAt(j, 0);
                int idEnTabla = (int) model.getValueAt(j, 2);
                if (archivo.getNombre().equals(nombreEnTabla) || archivo.getId() == idEnTabla) {
                    existe = true;
                    break;
                }
            }

            // Si no existe, agrega el archivo a la tabla
            if (!existe) {
                model.addRow(new Object[]{archivo.getNombre(), archivo.getLongitud(), archivo.getPosicioni()});
            }
        }
    }
    
    public Lista<Archivo> filtrarArchivos(int id_filtro) {
        Lista<Archivo> lista_filtrada = new Lista<>("Filtrada");

        for (int i = 0; i < this.archivos.size(); i++) {
            Archivo archivo = this.archivos.get(i);
            if (archivo.getId() == id_filtro) {
                lista_filtrada.append(archivo);
            }
        }
        return lista_filtrada;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creationButton;
    private javax.swing.JButton deletionButton;
    private javax.swing.JTextField deletionTextField;
    private javax.swing.JTextField fileFilterByIDField;
    private javax.swing.JButton filterButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField newFileContentField;
    private javax.swing.JTextField newFileIDField;
    private javax.swing.JTextField newFileIField;
    private javax.swing.JTextField newFileJField;
    private javax.swing.JTextField newFileNameField;
    private javax.swing.JTextField newFileSizeField;
    private javax.swing.JTable tablaAsignacionArchivos;
    // End of variables declaration//GEN-END:variables
}
