/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import Logica.Estructuras.Lista;
import Logica.Clases.Archivo;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.tree.TreeNode;

/**
 *
 * @author carlo_7ogoiii
 */
public class Pantalla extends javax.swing.JFrame {

    
    private Lista<Archivo> listaArchivos;
    private DefaultMutableTreeNode raiz;
    private int idSiguiente;
    
    
    public Pantalla(Lista<Archivo> listaArchivos) {
        initComponents();
        
        raiz = new DefaultMutableTreeNode("Raíz");
        treeDirectorio = new DefaultTreeModel(raiz);
        jTree1.setModel(treeDirectorio);
        this.listaArchivos = listaArchivos;
        idSiguiente = obtenerIdMasGrande() + 1;
    }
    
    DefaultTreeModel treeDirectorio;
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SDtable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        btnCrearArchivo = new javax.swing.JButton();
        btnCrearCarpeta = new javax.swing.JButton();
        btnEliminarCarpeta = new javax.swing.JButton();
        btnEliminarArchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        SDtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "2", "3", "4", "5", "6", "7", "8"},
                {"9", "10", "11", "12", "13", "14", "15", "16"},
                {"17", "18", "19", "20", "21", "22", "23", "24"},
                {"25", "26", "27", "28", "29", "30", "31", "32"},
                {"33", "34", "35", "36", "37", "38", "39", "40"},
                {"41", "42", "43", "44", "45", "46", "47", "48"},
                {"49", "50", "51", "52", "53", "54", "55", "56"},
                {"57", "58", "59", "60", "61", "62", "63", "64"}
            },
            new String [] {
                "", "", "", "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        SDtable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        SDtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SDtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(SDtable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 320, 440, 140);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Estado del SD");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 280, 130, 25);

        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTree1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 50, 440, 210);

        btnCrearArchivo.setText("Crear archivo");
        btnCrearArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearArchivo);
        btnCrearArchivo.setBounds(540, 50, 140, 27);

        btnCrearCarpeta.setText("Crear carpeta");
        btnCrearCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCarpetaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearCarpeta);
        btnCrearCarpeta.setBounds(540, 90, 140, 27);

        btnEliminarCarpeta.setText("Eliminar carpeta");
        btnEliminarCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCarpetaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarCarpeta);
        btnEliminarCarpeta.setBounds(800, 230, 140, 27);

        btnEliminarArchivo.setText("Eliminar archivo");
        btnEliminarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarArchivo);
        btnEliminarArchivo.setBounds(800, 190, 140, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public class CeldaColorEspecificoRenderer extends DefaultTableCellRenderer {

    private List<CeldaInfo> celdasColoreadas = new ArrayList<>();

    public void setColorCelda(int fila, int columna, Color color) {
        celdasColoreadas.add(new CeldaInfo(fila, columna, color));
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        c.setBackground(table.getBackground()); // Color predeterminado

        for (CeldaInfo celda : celdasColoreadas) {
            if (celda.fila == row && celda.columna == column) {
                c.setBackground(celda.color);
                break;
            }
        }

        return c;
    }

    public static class CeldaInfo {
        public int fila;
        public int columna;
        public Color color;

        public CeldaInfo(int fila, int columna, Color color) {
            this.fila = fila;
            this.columna = columna;
            this.color = color;
        }
    }
}
    
    private CeldaColorEspecificoRenderer renderer = new CeldaColorEspecificoRenderer(); // Instancia del renderizador

    public void cambiarColorCelda(int fila, int columna, Color color) {
        renderer.setColorCelda(fila, columna, color);
        SDtable.getColumnModel().getColumn(columna).setCellRenderer(renderer);
        SDtable.repaint();
    }
    
    
    
    private void SDtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SDtableMouseClicked

        int fila = SDtable.getSelectedRow();
        int columna = SDtable.getSelectedColumn();
        
        System.out.println(" Fila: " + fila + " Columna: " + columna);

        if (fila != -1 && columna != -1) {
            cambiarColorCelda(fila, columna, Color.YELLOW);
            String valorActual = (String) SDtable.getValueAt(fila, columna);
            String nuevoValor = JOptionPane.showInputDialog("Ingrese el nuevo valor:", valorActual);
            if (nuevoValor != null) {
                SDtable.setValueAt(nuevoValor, fila, columna);
            }
        }

    }//GEN-LAST:event_SDtableMouseClicked

    
    
    
    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        
        if (evt.getClickCount() == 2) { // Verifica si es doble clic
        DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
        
        if (nodoSeleccionado != null && nodoSeleccionado.getUserObject() != null && nodoSeleccionado.getChildCount() == 0) {
            Object userObject = nodoSeleccionado.getUserObject();
            if (userObject instanceof Archivo) { // Verifica si el objeto es de tipo Archivo
                Archivo archivo = (Archivo) userObject;
                String contenido = archivo.getContenido(); // Obtiene el contenido del archivo
                String texto = "Contenido del archivo: " + contenido;
                JOptionPane.showMessageDialog(this, texto);
            } else {
                JOptionPane.showMessageDialog(this, "El nodo no contiene un archivo válido o es una carpeta");
            }
        }
    }
        
    }//GEN-LAST:event_jTree1MouseClicked

    
    private int asignarID(){
        
        int id = 0;
        id = id + idSiguiente;
        return id;
        
    }
    
    
    public int obtenerIdMasGrande() {
    if (this.listaArchivos.size() == 0) {
        
        System.out.println("La lista está vacía");
        return 0;
    }

    int idMasGrande = this.listaArchivos.get(0).getId(); // Inicializa con el primer ID
    for (int i = 1; i < this.listaArchivos.size(); i++) {
        int idActual = this.listaArchivos.get(i).getId();
        if (idActual > idMasGrande) {
            idMasGrande = idActual;
        }
    }
    return idMasGrande;
}
    
    
    private void btnCrearArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearArchivoActionPerformed
        
        DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
        
        if(nodoSeleccionado == null){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una carpeta");
        }
        
        if(!(nodoSeleccionado.getUserObject() instanceof Archivo)){
            
            String nombre = JOptionPane.showInputDialog("Nombre del archivo:");
        if (nombre != null && !nombre.isEmpty()) {
            String contenido = JOptionPane.showInputDialog("Contenido del archivo:"); // O cualquier otro dato
            
            if (contenido != null && !contenido.isEmpty()){
                String strLongitud = JOptionPane.showInputDialog("Longitud del archivo (en bloques):");
                int longitud = Integer.parseInt(strLongitud);
                
                if (longitud > 0) {
                    
                Archivo archivo = new Archivo(nombre, asignarID(), longitud, 0, 0, contenido); // Crea una instancia de Archivo
                
                this.idSiguiente++;
                
                DefaultMutableTreeNode nuevoNodo = new DefaultMutableTreeNode(archivo); // Almacena el objeto en el nodo
                listaArchivos.append(archivo);
                
                    if (nodoSeleccionado == null) {
                        treeDirectorio.insertNodeInto(nuevoNodo, (DefaultMutableTreeNode) treeDirectorio.getRoot(), treeDirectorio.getChildCount(treeDirectorio.getRoot()));
                    } else {
                        treeDirectorio.insertNodeInto(nuevoNodo, nodoSeleccionado, treeDirectorio.getChildCount(nodoSeleccionado));}
            }
            }
        }
        
        } else{
            
            JOptionPane.showMessageDialog(this, "Debe seleccionar una carpeta");
        }
         
    }//GEN-LAST:event_btnCrearArchivoActionPerformed

    private void btnCrearCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCarpetaActionPerformed
        
        DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
        
        if(nodoSeleccionado == null){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una carpeta");
        }
        
        if(!(nodoSeleccionado.getUserObject() instanceof Archivo)){
        
        String nombre = JOptionPane.showInputDialog("Nombre de la carpeta:");
        if (nombre != null && !nombre.isEmpty()) {
            DefaultMutableTreeNode nuevoNodo = new DefaultMutableTreeNode(nombre);
            if (nodoSeleccionado == null) {
                // Si no hay nodo seleccionado, agrega a la raíz
                treeDirectorio.insertNodeInto(nuevoNodo, (DefaultMutableTreeNode) treeDirectorio.getRoot(), treeDirectorio.getChildCount(treeDirectorio.getRoot()));
            } else {
                // Si hay nodo seleccionado, agrega como hijo
                treeDirectorio.insertNodeInto(nuevoNodo, nodoSeleccionado, treeDirectorio.getChildCount(nodoSeleccionado));
            }
        }
        
        }else{
            
            JOptionPane.showMessageDialog(this, "Debe seleccionar una carpeta");
        }
        
        
        
    }//GEN-LAST:event_btnCrearCarpetaActionPerformed

    private void btnEliminarCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCarpetaActionPerformed
        
        DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();

        if (nodoSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar la carpeta a borrar");
            return;
        }

        if (!(nodoSeleccionado.getUserObject() instanceof Archivo)) {
            int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea borrar la carpeta \"" + nodoSeleccionado.getUserObject() + "\" y todo su contenido?", "Confirmar borrado", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                DefaultMutableTreeNode padre = (DefaultMutableTreeNode) nodoSeleccionado.getParent();
                if (padre != null) {
                    // Borrar los archivos asociados a esta carpeta
                    borrarArchivosDeCarpeta(nodoSeleccionado);

                    // Borrar el nodo del árbol
                    treeDirectorio.removeNodeFromParent(nodoSeleccionado);
                    treeDirectorio.reload(padre); // Recarga el nodo padre para actualizar la vista
                } else {
                    JOptionPane.showMessageDialog(this, "No se puede borrar la raíz del árbol.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Solo puede borrar carpetas.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnEliminarCarpetaActionPerformed

    private void btnEliminarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarArchivoActionPerformed

    
    private void borrarArchivosDeCarpeta(DefaultMutableTreeNode carpetaNodo) {
    if (carpetaNodo instanceof DefaultMutableTreeNode) {
        Enumeration<TreeNode> hijos = carpetaNodo.children(); // Cambiado a Enumeration<TreeNode>
        while (hijos.hasMoreElements()) {
            TreeNode hijo = hijos.nextElement(); // Cambiado a TreeNode
            if (hijo instanceof DefaultMutableTreeNode) { // Verifica si es DefaultMutableTreeNode
                DefaultMutableTreeNode defaultHijo = (DefaultMutableTreeNode) hijo; // Casting seguro
                Object userObject = defaultHijo.getUserObject();
                if (userObject instanceof Archivo) {
                    Archivo archivo = (Archivo) userObject;
                    borrarArchivo(archivo.getId());
                } else {
                    borrarArchivosDeCarpeta(defaultHijo); // Llama recursivamente con DefaultMutableTreeNode
                }
            }
        }
    } else {
        System.err.println("Error: carpetaNodo no es DefaultMutableTreeNode");
        JOptionPane.showMessageDialog(this, "Error al borrar la carpeta.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    public Lista<Archivo> filtrarArchivos(int id_filtro) {
        Lista<Archivo> lista_filtrada = new Lista<>("Filtrada");
        for (int i = 0; i < this.listaArchivos.size(); i++) {
            Archivo archivo = this.listaArchivos.get(i);
            if (archivo.getId() == id_filtro) {
                lista_filtrada.append(archivo);
            }
        }
        return lista_filtrada;
    }

    public void borrarArchivo(int idArchivo) {

    boolean existe = false;

    for (int i = listaArchivos.size() - 1; i >= 0; i--) { // Recorre en orden inverso
        Archivo archivo = listaArchivos.get(i);
        if (archivo.getId() == idArchivo) {
            listaArchivos.deleteByIndex(i);
            existe = true;
            System.out.println(archivo.getNombre() + " eliminado");
        }
    }

    if (!existe) {
        System.out.println("No existe");
    }
}

    
    
    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SDtable;
    private javax.swing.JButton btnCrearArchivo;
    private javax.swing.JButton btnCrearCarpeta;
    private javax.swing.JButton btnEliminarArchivo;
    private javax.swing.JButton btnEliminarCarpeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
